# Generated by Django 5.2 on 2025-04-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MOD', 'Moderator'), ('AUTHOR', 'Author'), ('EDITOR', 'Editor'), ('REVIEWER', 'Reviewer'), ('CONTRIBUTOR', 'Contributor'), ('MEMBER', 'Member'), ('GUEST', 'Guest'), ('MANAGER', 'Manager'), ('DEVELOPER', 'Developer')], default='DEVELOPER', max_length=300)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('Bio', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
