# Generated by Django 5.2 on 2025-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
