# Generated by Django 5.2 on 2025-04-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('TaskProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'To_Do'), ('INPROGRESS', 'In_Progress'), ('INREVIEW', 'In_Review'), ('DONE', 'Done'), ('BLOCK', 'Block')], default='To_Do', max_length=244)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='Low', max_length=255)),
                ('due_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.CharField(max_length=233)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.usermodel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='TaskProject.projectmodel')),
            ],
        ),
    ]
