# Generated by Django 5.2 on 2025-04-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVATE', 'Activate'), ('ON_HOLD', 'On_hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='Planning', max_length=40)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='Account.usermodel')),
                ('members', models.ManyToManyField(related_name='team', to='Account.usermodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
